# Generated by Django 6.1 on 2026-08-13 22:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام فهرست')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_id', models.CharField(max_length=20, verbose_name='شناسه IMDb')),
                ('title_type', models.CharField(choices=[('movie', 'فیلم'), ('tv', 'سریال')], max_length=10)),
                ('title_name', models.CharField(blank=True, max_length=255)),
                ('poster_url', models.URLField(blank=True, null=True)),
                ('total_episodes', models.PositiveIntegerField(default=1, verbose_name='کل قسمت\u200cها')),
                ('status', models.CharField(choices=[('plan_to_watch', 'قصد دارم تماشا کنم'), ('watching', 'در حال تماشا'), ('completed', 'مشاهده\u200cشده'), ('paused', 'متوقف\u200cشده'), ('dropped', 'رهاشده')], default='plan_to_watch', max_length=20)),
                ('is_favorite', models.BooleanField(default=False, verbose_name='مورد علاقه')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_titles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'imdb_id')},
            },
        ),
        migrations.CreateModel(
            name='PlaylistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='watch.customplaylist')),
                ('user_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_items', to='watch.usertitle')),
            ],
            options={
                'unique_together': {('playlist', 'user_title')},
            },
        ),
        migrations.CreateModel(
            name='WatchedEpisode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_number', models.PositiveIntegerField()),
                ('episode_number', models.PositiveIntegerField()),
                ('watched_at', models.DateTimeField(auto_now_add=True)),
                ('user_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watched_episodes', to='watch.usertitle')),
            ],
            options={
                'unique_together': {('user_title', 'season_number', 'episode_number')},
            },
        ),
    ]
