# Generated by Django 6.1 on 2026-08-14 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='favorite_items',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='watched_movies_count',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='watched_shows_count',
        ),
    ]
